package configs

const (
	HTTP_PORT = "HTTP_PORT"

	MONGO_URI      = "MONGO_URI"
	MONGO_USER     = "MONGO_USER"
	MONGO_PASSWORD = "MONGO_PASSWORD"
	MONGO_DATABASE = "MONGO_DATABASE"

	MONGO_CARTS_COLLECTION    = "carts"
	MONGO_ORDERS_COLLECTION   = "orders"
	MONGO_PRODUCTS_COLLECTION = "products"
)
